# Generated by Django 4.1.3 on 2023-03-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='view_counts',
            field=models.IntegerField(default=0),
        ),
    ]
