# Generated by Django 4.1.3 on 2023-03-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0002_thread_view_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
