# Generated by Django 4.1.3 on 2023-03-08 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0003_thread_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_folder.thread')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
