# Generated by Django 4.1.3 on 2023-03-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0004_remove_thread_like_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='target_thread',
            new_name='target',
        ),
    ]
