# Generated by Django 4.1.3 on 2023-03-10 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0006_likeforpost_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', through='app_folder.LikeForPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
