# Generated by Django 4.1.3 on 2023-03-10 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0008_likeforcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', through='app_folder.LikeForComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_likes',
            field=models.ManyToManyField(blank=True, related_name='thread_likes', through='app_folder.LikeForPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
