# Generated by Django 4.1.3 on 2023-03-11 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_folder', '0009_remove_thread_likes_comment_comment_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_image',
        ),
    ]
